import {describe,it,expect,vi} from 'vitest'
import {DBXTransport} from './dbx-transport'
import {clearDBXResourceDiscovery} from './dbx-resource-discovery'
describe('DBX transport contract',()=>{
 it('sends GVR for namespaced list and cluster detail',async()=>{const i=vi.fn().mockResolvedValue({resources:[{group:'apps',version:'v1',resource:'deployments',kind:'Deployment',namespaced:true},{group:'',version:'v1',resource:'nodes',kind:'Node',namespaced:false}]});const t=new DBXTransport(i,'c');await t.request('/api/v1/deployments/default','GET');expect(i).toHaveBeenLastCalledWith('resource/list',expect.objectContaining({group:'apps',version:'v1',resource:'deployments',namespace:'default'}));await t.request('/api/v1/nodes/n1','GET');expect(i).toHaveBeenLastCalledWith('resource/get',expect.objectContaining({resource:'nodes',name:'n1',namespace:undefined}))})
 it('maps patch and delete preconditions',async()=>{const i=vi.fn().mockResolvedValue({resources:[{version:'v1',resource:'pods',kind:'Pod',namespaced:true}],metadata:{uid:'u',resourceVersion:'v'}});clearDBXResourceDiscovery('c');const t=new DBXTransport(i,'c');await t.request('/api/v1/pods/default/p1','PATCH',{spec:{x:1}});expect(i).toHaveBeenCalledWith('resource/patch',expect.objectContaining({patch:{spec:{x:1}}}));await t.request('/api/v1/pods/default/p1','DELETE');expect(i).toHaveBeenCalledWith('resource/delete',expect.objectContaining({uid:'u',resourceVersion:'v'}))})
 it('preserves custom resource identity in search results',async()=>{const i=vi.fn().mockResolvedValue({items:[{id:'u',name:'one',namespace:'default',group:'example.com',version:'v1',resource:'widgets'},{id:'crd',name:'widgets.example.com',namespace:'',group:'apiextensions.k8s.io',version:'v1',resource:'customresourcedefinitions'}],warnings:[],truncated:false});const t=new DBXTransport(i,'c');await expect(t.request('/api/v1/search?q=one','GET')).resolves.toMatchObject({results:[{name:'one',resourceType:'widgets.example.com',customResource:true,group:'example.com',version:'v1'},{name:'widgets.example.com',resourceType:'crds',customResource:false}]})})
 it('preserves custom resource identity in favorites while keeping built-ins plain',async()=>{const custom={resource:{group:'example.com',version:'v1',resource:'widgets',kind:'Widget',namespaced:true},object:{metadata:{name:'one',namespace:'default'}}};const builtin={resource:{group:'apps',version:'v1',resource:'deployments',kind:'Deployment',namespaced:true},object:{metadata:{name:'web',namespace:'default'}}};const i=vi.fn().mockImplementation(async method=>method==='favorite/list'?{items:[custom,builtin]}:{});const t=new DBXTransport(i,'c');await expect(t.request('/api/v1/preferences/favorites','GET')).resolves.toMatchObject([{resourceType:'widgets.example.com',customResource:true},{resourceType:'deployments',customResource:false}])})
 it('uses the original GVR when removing a favorite',async()=>{let updateParams:unknown;const i=vi.fn().mockImplementation(async (method,params)=>{if(method==='kube/discover')return {resources:[{group:'example.com',version:'v1beta1',resource:'widgets',kind:'Widget',namespaced:true},{group:'example.com',version:'v1',resource:'widgets',kind:'Widget',namespaced:true}]};if(method==='favorite/update'){updateParams=params;return {items:[]}};return {}});clearDBXResourceDiscovery('c');const t=new DBXTransport(i,'c');await t.request('/api/v1/preferences/favorites/remove','POST',{resourceType:'widgets.example.com',group:'example.com',version:'v1',namespace:'default',resourceName:'one'});expect(updateParams).toMatchObject({item:{resource:{group:'example.com',version:'v1',resource:'widgets'}},remove:true})})
})
